### ISSUE TITLE
Game search via developers does not return all results

### ISSUE THREAD

**Issue by isg89** [mythril-io/mythril#1]
## Overview of the problem

This is about searching/filtering games.

## Description

Searching for games by selecting a developer does not return results for games that are co-developed.

## Expected behavior

All games for the selected developer should be returned.

## Actual behavior

Games that were co-developed by a developer are not included in return set.

**Comment by James-N-M** [comment]
Hey man @ig-89 ill try and give this a go if you havnt already solved it 👾

**Comment by isg89** [comment]
Hey @James-N-M , yeah go for it. I just haven't made the time to fix it.

**Comment by rickyjanuari** [comment]
hey @ig-89 you can share database seed?

**Comment by isg89** [comment]
Hey @rickyjanuari, sure I will try to provide one tomorrow. I've just been preoccupied with developing the forums.

**Comment by rickyjanuari** [comment]
Ok Thanks @ig-89  👍

**Comment by isg89** [comment]
@rickyjanuari Since I don't have any of the seeding/factory classes already created, I will probably postpone creating them until after the forums have been finished with development (should be soon, ~1-2 weeks). Thanks!

**Comment by James-N-M** [comment]
@ig-89 jamesm0025@gmail.com let me know if you need a hand writing the seeders/factory classes

**Comment by isg89** [comment]
@James-N-M Yeah if you could help with creating them that would be great!

**Comment by James-N-M** [comment]
I'll have a pull request up tonight to get them started @ig-89

**Comment by James-N-M** [comment]
@ig-89 do you push all your compiled stuff from running npm run dev to production ? or do you compile on your server ? just wondering if i should add to .gitignore

**Comment by isg89** [comment]
@James-N-M On the server. I use Laravel Forge, so I just push the code to git and Forge, I believe uses a git hook, and then runs whatever commands are required.

**Comment by James-N-M** [comment]
If you could add the public js and css folders to the .gitignore thatd be awesome
